Temptative implement of SSL auth support
senx/warp10-plugin-py4j pull request #3
Opened 2022-04-26 14:13 UTC by randomboolean

2022-04-26 14:24 UTC, hbs requested changes

2022-04-26 14:24 UTC, hbs commented on src/main/java/io/warp10/plugins/py4j/Py4JWarp10Plugin.java
> +          ssf = SSLServerSocketFactory.getDefault();
What is the certificate used in that case?

2022-04-26 14:24 UTC, hbs commented on src/main/java/io/warp10/plugins/py4j/Py4JWarp10Plugin.java
> +import io.warp10.sensision.jarjar.org.eclipse.jetty.util.ssl.SslContextFactory;
This is not the SslContextFactory which should be used.

2022-04-26 14:24 UTC, hbs commented on src/main/java/io/warp10/plugins/py4j/Py4JWarp10Plugin.java
>  //
Add a README file describing how SSL should be set up, from certificate creation to configuration of the plugin.

Simply document the steps you followed during testing.

2022-05-06 12:33 UTC, randomboolean commented on src/main/java/io/warp10/plugins/py4j/Py4JWarp10Plugin.java
> +          ssf = SSLServerSocketFactory.getDefault();
this case now raises a RuntimeException

2022-05-13 14:05 UTC, steven-gueguen requested changes

2022-05-13 14:05 UTC, stggn commented on README.md
> +params = GatewayParameters('localhost', 25333, auto_convert=True, auth_token="your-token")
Either remove the auth_token in this example or and it to the configuration example

2022-05-13 14:05 UTC, stggn commented on README.md
> +```
Set language as `properties`

2022-05-13 14:05 UTC, stggn commented on README.md
> +```
Set language as `properties`

2022-05-13 14:05 UTC, stggn commented on README.md
> +params = GatewayParameters('localhost', 25333, auto_convert=True, auth_token="your-token")
Use '127.0.0.1' instead of 'localhost'

2022-05-13 14:05 UTC, stggn commented on README.md
> +stack.pop()
Add print

2022-05-13 14:05 UTC, stggn commented on build.gradle
> +    compileOnly 'io.warp10:warpscript:2.8.+'
Upgrade to 2.10.1

2022-05-13 14:05 UTC, stggn commented on src/main/java/io/warp10/plugins/py4j/Py4JWarp10Plugin.java
> +//   Copyright 2018-22  SenX S.A.S.
Use YYYY format, ie:2022

2022-05-13 14:05 UTC, steven-gueguen commented on src/main/java/io/warp10/plugins/py4j/Py4JWarp10Plugin.java
> +  private SslContextFactory getSslContextFactory(Properties props, String prefix) throws Exception {
Remove prefix if unused

2022-05-13 15:38 UTC, steven-gueguen approved these changes

2022-05-17 11:33 UTC, merged